version: '3'
services:
  db-server:
    restart: always
    image: "postgres:11-alpine"
    volumes:
      - "/srv/dbdata:/var/lib/postgresql/data"
    env_file:
      - env_file
    networks:
      - db_nw
  app:
    restart: always
    build: .
    env_file:
      - env_file
    entrypoint: /app/entrypoint.sh
    networks:
      - db_nw
      - web_nw
    depends_on:
      - db-server
  nginx:
    restart: always
    image: "nginx:1.18-alpine"
    ports:
      - "8080:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - web_nw
    depends_on: 
      - app
networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge
    #volumes:
    #  dbdata:
